steps:
- name: 'python:3.9-alpine'
  secretEnv: ['SSH_KEY']
  entrypoint: 'sh'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
    apk add git
    pip install -r requirements.txt
    python check_diff.py
  env:
    - 'HEAD_BRANCH=$_HEAD_BRANCH'
    - 'BASE_BRANCH=$_BASE_BRANCH'
    - 'REPO_URL=$_HEAD_REPO_URL'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github_ssh_key/versions/latest
    env: 'SSH_KEY'
options:
  logging: CLOUD_LOGGING_ONLY
